name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  lint_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Cache Poetry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pypoetry
            ~/.cache/pip
          key: poetry-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install Poetry
        run: pipx install poetry==1.8.3

      - name: Install deps
        run: |
          poetry lock --no-cache
          poetry install

      # .env НЕ создаём — тесты самодостаточные благодаря conftest.py

      - name: Ruff
        run: poetry run ruff check .

      - name: Black (check)
        run: poetry run black --check .

      - name: Isort (check)
        run: poetry run isort --check-only .

      - name: Mypy
        run: poetry run mypy app

      - name: Pytest (unit only)
        run: poetry run pytest --maxfail=1 --disable-warnings -q --cov=app
